# Generated by Django 5.1.1 on 2024-09-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_data_ultima_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
