# Generated by Django 5.1.1 on 2024-09-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_data_vencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_saida', models.DateField(auto_now_add=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.entradaproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='estoque.produto')),
            ],
        ),
    ]
